### PR TITLE
This pull request is update for links page

### PR DESCRIPTION
**Pull request by Nirmitjatana**
New UI is given to links page at the same time automating it with instagram API

### CODE REVIEW

**Comment by Geek-ubaid** [comment]
where is the links attached to the home page @Nirmitjatana

**Comment by L04DB4L4NC3R** [comment]
> where is the links page attached to the home page @Nirmitjatana

+1

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R I have linked the page to navbar of index page

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R I have linked the page to navbar of index page

I can't see the nav link in the deploy preview

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R check out!

**Comment by L04DB4L4NC3R** [comment]
The fix is not working @Nirmitjatana

**Comment by L04DB4L4NC3R** [comment]
> The fix is not working @Nirmitjatana

Working for firefox but after hard refresh, the website resets on qutebrowser

**Comment by L04DB4L4NC3R** [comment]
@Nirmitjatana still cannot see the photos being popped up. Any updates? This PR is going stale.

**Comment by Nirmitjatana** [comment]
@Geek-ubaid I have all the required changes

**Comment by L04DB4L4NC3R** [comment]
@Nirmitjatana here are the changes required:

- [ ] Have the hover text be on the middle of the card
- [ ] Onclick redirect to the post is not working
- [ ] Handle posts with no link by No-op
- [ ] Get the backend on https://kaffeine.herokuapp.com so that is does not die after 30 mins of inactivity
- [ ] Add pagination and not show more than 9 posts per page

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R well I am not getting any redirect link from the Backend. please look into it.

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R https://kaffeine.herokuapp.com shows CORS

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R backend supplies with latest 25 posts only, do you still need me to add pagination?

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R backend supplies with latest 25 posts only, do you still need me to add pagination?

No need then

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R https://kaffeine.herokuapp.com shows CORS

Describe what you added

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.

@Pragati1610 @mdhishaamakhtar  explanation?

**Comment by mdhishaamakhtar** [comment]
> > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> 
> @Pragati1610 @mdhishaamakhtar  explanation?

The link is always live i5s on my heroku.

**Comment by mdhishaamakhtar** [comment]
> > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > 
> > @Pragati1610 @mdhishaamakhtar  explanation?
> 
> The link is always live i5s on my heroku. 

I am not able to understand the issue here can we call tomorrow once?

**Comment by L04DB4L4NC3R** [comment]
> > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > 
> > 
> > @Pragati1610 @mdhishaamakhtar  explanation?
> 
> The link is always live i5s on my heroku.

The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link of the original post being sent in the body

**Comment by mdhishaamakhtar** [comment]
> > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > 
> > > 
> > > @Pragati1610 @mdhishaamakhtar  explanation?
> > 
> > The link is always live i5s on my heroku.
> 
> The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body

Thats because the post does not have a url in the caption. We have a lot of posts like that.

**Comment by Nirmitjatana** [comment]
> > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > 
> > > > 
> > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > 
> > > 
> > > The link is always live i5s on my heroku.
> > 
> > 
> > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> 
> Thats because the post does not have a url in the caption. We have a lot of posts like that.

In case there is no link in the caption can you send link of the original post?

**Comment by mdhishaamakhtar** [comment]
> > > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > > 
> > > > > 
> > > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > > 
> > > > 
> > > > The link is always live i5s on my heroku.
> > > 
> > > 
> > > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> > 
> > Thats because the post does not have a url in the caption. We have a lot of posts like that.
> 
> In case there is no link in the caption can you send link of the original post?

That is being already sent as the media_url for all the posts

**Comment by Nirmitjatana** [comment]
> > @L04DB4L4NC3R https://kaffeine.herokuapp.com shows CORS
> 
> Describe what you added

https://dsclinks.herokuapp.com/ this link works fine. Do we need to change it?

**Comment by Nirmitjatana** [comment]
> > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > 
> > > > 
> > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > 
> > > The link is always live i5s on my heroku.
> > 
> > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> 
> Thats because the post does not have a url in the caption. We have a lot of posts like that. 

I believe that is link of the hosted image from the Facebook/instagram API. But we need link to the particular post.

**Comment by mdhishaamakhtar** [comment]
> > > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > > 
> > > > > 
> > > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > > 
> > > > The link is always live i5s on my heroku.
> > > 
> > > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> > 
> > Thats because the post does not have a url in the caption. We have a lot of posts like that. 
> 
> I believe that is link of the hosted image from the Facebook/instagram API. But we need link to the particular post.

We don't get that back from the API. I can send you an empty url field

**Comment by Geek-ubaid** [comment]
@Nirmitjatana added some more issues to the list [here](https://github.com/GDGVIT/DSC-Site-2019/pull/32#issuecomment-643751920)

**Comment by Nirmitjatana** [comment]
> > > > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > > > 
> > > > > > 
> > > > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > > > 
> > > > > The link is always live i5s on my heroku.
> > > > 
> > > > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> > > 
> > > Thats because the post does not have a url in the caption. We have a lot of posts like that. 
> > 
> > I believe that is link of the hosted image from the Facebook/instagram API. But we need link to the particular post.
> 
> We don't get that back from the API. I can send you an empty url field
> 

We need a link that takes users to instagram/Facebook on that post. Is that possible?

**Comment by L04DB4L4NC3R** [comment]
> > > > > > > @L04DB4L4NC3R well I am not getting any redirect link from the Backend, please look into it.
> > > > > > 
> > > > > > 
> > > > > > @Pragati1610 @mdhishaamakhtar  explanation?
> > > > > 
> > > > > 
> > > > > The link is always live i5s on my heroku.
> > > > 
> > > > 
> > > > The issue is that when we click on the post, we need to be redirected to the URL in the captions. But nirmit says there is no link being sent in the body
> > > 
> > > 
> > > Thats because the post does not have a url in the caption. We have a lot of posts like that.
> > 
> > 
> > In case there is no link in the caption can you send link of the original post?
> 
> That is being already sent as the media_url for all the posts

@Nirmitjatana check the media_url for the same

**Comment by mdhishaamakhtar** [comment]
[X] The backend wont die due to inactivity I have it on a paid dyno due to credits.

**Comment by L04DB4L4NC3R** [comment]
> @Nirmitjatana here are the changes required:
> 
> * [x]  Have the hover text be on the middle of the card
> * [ ]  Onclick redirect to the post is not working
> * [ ]  Handle posts with no link by No-op
> * [x]  Get the backend on https://kaffeine.herokuapp.com so that is does not die after 30 mins of inactivity
> * [x]  Add pagination and not show more than 9 posts per page
> * [ ]  Make the animation vector transparent interfering with the text
> * [ ]  some card have only text no image, check the api
> * [ ]  Add loader to the links site page

@mdhishaamakhtar @

> @Nirmitjatana here are the changes required:
> 
> * [x]  Have the hover text be on the middle of the card
> * [ ]  Onclick redirect to the post is not working
> * [ ]  Handle posts with no link by No-op
> * [x]  Get the backend on https://kaffeine.herokuapp.com so that is does not die after 30 mins of inactivity
> * [x]  Add pagination and not show more than 9 posts per page
> * [ ]  Make the animation vector transparent interfering with the text
> * [ ]  some card have only text no image, check the api
> * [ ]  Add loader to the links site page

@mdhishaamakhtar @Nirmitjatana @Pragati1610 where are we at with this?

**Comment by mdhishaamakhtar** [comment]
Apps are on heroku itself. As for photos we are returning whatever instagram gives us. Pagination incoming

**Comment by L04DB4L4NC3R** [comment]
> Apps are on heroku itself. As for photos we are returning whatever instagram gives us. Pagination incoming
Pagination is not needed if only 25 posts are being sent

**Comment by Nirmitjatana** [comment]
@L04DB4L4NC3R I have made all the changes except redirect and they are ready to push

**Comment by Geek-ubaid** [comment]
> @L04DB4L4NC3R I have made all the changes except redirect and they are ready to push

@Nirmitjatana I cannot see the last three points [here](https://github.com/GDGVIT/DSC-Site-2019/pull/32#issuecomment-643751920) being corrected

**Pull request merged**
